steps:
  # Step 1: Building the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'my-flask-app', '.']

  # Step 2: Tagging the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'my-flask-app', '166673582388.dkr.ecr.us-east-1.amazonaws.com/my-flask-app']

  # Step 3: Authenticating with AWS ECR
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 166673582388.dkr.ecr.us-east-1.amazonaws.com

  # Step 4: Pushing the Docker image to Amazon ECR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '166673582388.dkr.ecr.us-east-1.amazonaws.com/my-flask-app']
