version: 0.2

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t jaisankar-flask-app .
      - echo "Tagging Docker image..."
      - docker tag jaisankar-flask-app:latest 211125601405.dkr.ecr.us-east-1.amazonaws.com/jaisankar-flask-app:latest
 
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 166673582388.dkr.ecr.us-east-1.amazonaws.com/jaisankar-flask-app:latest
 
artifacts:
  files: []
